version: '3.9'

services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:3000
    command: npm start
    volumes:
      - ./src:/app/src